begin;
-- No fixture data survives the transaction, including temporary auth users.
select set_config('crm.test_owner',gen_random_uuid()::text,true);
select set_config('crm.test_other',gen_random_uuid()::text,true);
insert into auth.users(id) values(current_setting('crm.test_owner')::uuid),(current_setting('crm.test_other')::uuid);
insert into public.presentation_admins(user_id,role) values(current_setting('crm.test_owner')::uuid,'owner'),(current_setting('crm.test_other')::uuid,'owner');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('crm.test_owner'),'role','authenticated')::text,true);
set local role authenticated;
do $$ declare c uuid; r jsonb; s jsonb:='{"next_followup":null,"has_replied":false,"engagement":"ACTIVE"}';before_count int;begin
 if public.crm_suggestion_rule('WON',s,false,now()) is not null then raise exception 'Closed suggestion';end if;
 if public.crm_suggestion_rule('REPLIED',s||jsonb_build_object('next_followup',now()-interval '1 day'),false,now()) is not null then raise exception 'Overdue task duplicates';end if;
 if public.crm_suggestion_rule('REPLIED',s,false,now()) is distinct from 'REPLIED_NEEDS_ACTION' then raise exception 'Reply rule';end if;
 if public.crm_suggestion_rule('MEETING',s,false,now()) is distinct from 'MEETING_NEEDS_ACTION' then raise exception 'Meeting rule';end if;
 if public.crm_suggestion_rule('PROPOSAL',s||'{"engagement":"HOT"}',true,now()) is distinct from 'HOT_LEAD_IDLE' then raise exception 'HOT rule';end if;
 if public.crm_suggestion_rule('QUALIFIED',s,false,now()) is not null or public.crm_suggestion_rule('QUALIFIED',s,true,now()) is not null then raise exception 'Retired qualification rule still active';end if;
 if public.crm_suggestion_rule('PRESENTATION_VIEWED',s||jsonb_build_object('last_visit',now()-interval '3 days'),true,now()) is distinct from 'VIEWED_NO_REPLY' then raise exception 'Visit boundary';end if;
 if public.crm_suggestion_rule('PRESENTATION_VIEWED',s||jsonb_build_object('last_visit',now()-interval '3 days'+interval '1 second'),true,now()) is not null then raise exception 'Visit too early';end if;
 if public.crm_suggestion_rule('CONTACTED',s,true,now()) is not null then raise exception 'Missing visits fabricated';end if;
 if public.crm_suggestion_rule('CONTACTED',s||jsonb_build_object('last_contact',now()-interval '7 days','has_checked_visit',false,'tracking_enabled',true),true,now()) is distinct from 'CONTACTED_NOT_VIEWED' then raise exception 'No checked visit suggestion';end if;
 if public.crm_suggestion_rule('CONTACTED',s||jsonb_build_object('last_contact',now()-interval '7 days','has_checked_visit',true,'tracking_enabled',true),true,now()) is not null then raise exception 'Historical visit ignored';end if;
 if public.crm_suggestion_rule('CONTACTED',s||jsonb_build_object('last_contact',now()-interval '7 days','has_checked_visit',false,'tracking_enabled',false),true,now()) is not null then raise exception 'Disabled tracking claim';end if;
 if public.crm_suggestion_rule('PROPOSAL',s||'{"visits":3}',true,now()) is distinct from 'MULTIPLE_VIEWS' then raise exception 'Repeated visits';end if;
 if public.crm_suggestion_rule('PRESENTATION_VIEWED',s||jsonb_build_object('last_visit',now()-interval '4 days','has_replied',true),true,now()) is not null then raise exception 'Reply ignored';end if;
 insert into public.crm_companies(owner_id,company_name,pipeline_status) values(auth.uid(),'Suggestion fixture','REPLIED') returning id into c;
 perform set_config('crm.test_company',c::text,true);
 r:=public.crm_suggestions();if (r->>'total')::int<>1 then raise exception 'Missing candidate';end if;
 select count(*) into before_count from public.crm_activities where company_id=c;
 perform public.crm_set_suggestion_state(c,'REPLIED_NEEDS_ACTION','snooze');
 if (public.crm_suggestions()->>'total')::int<>0 or (public.crm_suggestions(1,true)->>'total')::int<>1 then raise exception 'Snooze filtering';end if;
 if (select dismissed_until from public.crm_suggestion_state where company_id=c)<>now()+interval '24 hours' then raise exception 'Snooze duration';end if;
 update public.crm_suggestion_state set dismissed_until=now()-interval '1 second' where company_id=c;
 if (public.crm_suggestions()->>'total')::int<>1 then raise exception 'Snooze expiry';end if;
 perform public.crm_set_suggestion_state(c,'REPLIED_NEEDS_ACTION','dismiss');
 perform public.crm_set_suggestion_state(c,'REPLIED_NEEDS_ACTION','dismiss');
 if (public.crm_suggestions()->>'total')::int<>0 then raise exception 'Dismiss filtering';end if;
 perform public.crm_set_suggestion_state(c,'REPLIED_NEEDS_ACTION','restore');
 if (public.crm_suggestions()->>'total')::int<>1 then raise exception 'Restore failed';end if;
 if (select count(*) from public.crm_activities where company_id=c)<>before_count then raise exception 'History changed';end if;
 insert into public.crm_followups(owner_id,company_id,title,due_at) values(auth.uid(),c,'Already pending',now()-interval '1 day');
 if (public.crm_suggestions()->>'total')::int<>0 then raise exception 'Existing task duplicated';end if;
 insert into public.crm_companies(owner_id,company_name,pipeline_status) select auth.uid(),'Paged suggestion '||i,'MEETING' from generate_series(1,12) i;
 r:=public.crm_suggestions();if jsonb_array_length(r->'items')<>10 or (r->>'total')::int<>12 then raise exception 'Page cap';end if;
 if jsonb_array_length(public.crm_suggestions(2)->'items')<>2 then raise exception 'Second page';end if;
 update public.crm_companies set archived_at=now() where company_name like 'Paged suggestion%';
 if (public.crm_suggestions()->>'total')::int<>0 then raise exception 'Archived leaked';end if;
 begin perform public.crm_set_suggestion_state(c,'bogus','dismiss');raise exception 'Invalid rule accepted';exception when invalid_parameter_value then null;end;
 perform set_config('request.jwt.claims',json_build_object('sub',current_setting('crm.test_other'),'role','authenticated')::text,true);
 if exists(select 1 from public.crm_suggestion_state) or (public.crm_suggestions()->>'total')::int<>0 then raise exception 'Other owner data leaked';end if;
 begin perform public.crm_set_suggestion_state(c,'REPLIED_NEEDS_ACTION','dismiss');raise exception 'Other owner write';exception when insufficient_privilege then null;end;
 begin insert into public.crm_suggestion_state(company_id,owner_id,rule) values(c,auth.uid(),'HOT_LEAD_IDLE');raise exception 'Forged company accepted';exception when insufficient_privilege then null;end;
end $$;
reset role;
set local role anon;
do $$ begin
 begin perform public.crm_suggestions();raise exception 'Anonymous execution';exception when insufficient_privilege then null;end;
 begin perform * from public.crm_suggestion_state;raise exception 'Anonymous read';exception when insufficient_privilege then null;end;
end $$;
rollback;
select 'Suggestion rules, bounds, pagination, state, history preservation and two-owner/anonymous RLS passed' result;
