import {test,expect} from '@playwright/test';
const id='22222222-2222-4222-8222-222222222222';
async function fixture(page){let company={id,company_name:'Fixture Company',services:[],priority:'HIGH',fit:'HIGH',pipeline_status:'WON',version:1},notes=[],clients=[],projects=[],calls=[],failNote=true,failProject=true;
 await page.route('**/api/admin?*',route=>{const u=new URL(route.request().url()),a=u.searchParams.get('action'),body=route.request().method()==='POST'?route.request().postDataJSON():null;calls.push({a,body});let data={items:[]};
 if(a==='me')data={email:'owner@example.test'};if(a==='crm-detail')data={company};if(a==='crm-list')data={companies:[company],total:1,page:1,pageSize:25};if(a==='crm-notes')data={items:notes};if(a==='crm-client')data={item:clients[0]||null};if(a==='crm-projects')data={items:projects};
 if(a==='crm-website-metadata')data={data:{website:body.website,company_name:'Reviewed website name',short_description:'Public description'}};
 if(a==='crm-duplicates')data={items:[company]};
 if(a==='crm-note-save'){if(failNote){failNote=false;return route.fulfill({status:502,json:{error:'Notes temporarily unavailable'}});}notes=[{id,content:body.content,created_at:new Date().toISOString()}];data={item:notes[0]};}
 if(a==='crm-client-convert'){clients=[{company_id:id,active:true,account_notes:'',version:1,client_since:'2026-09-22'}];data={item:clients[0]};}
 if(a==='crm-project-save'){if(failProject){failProject=false;return route.fulfill({status:409,json:{error:'Project unavailable. Retry.'}});}projects=[{...body,id,version:1}];data={item:projects[0]};}
 if(a==='crm-global-search')data={items:[{kind:'Company',title:company.company_name,url:'/admin/leads/'+id}]};
 return route.fulfill({json:data});});return {calls};}
test('quick note and client project failures preserve drafts, save safely and fit mobile',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page);await page.setViewportSize({width:390,height:844});await page.goto('/admin/leads/'+id);await expect(page.getByRole('button',{name:'Search / Ctrl+K'})).toBeVisible();await page.getByRole('button',{name:'+ Note',exact:true}).click();const note=page.locator('#quick-note');await note.getByLabel('Note',{exact:true}).fill('Keep <my> note');await note.getByRole('button',{name:'Save note'}).click();await expect(note).toContainText('Notes temporarily unavailable');await expect(note.getByLabel('Note',{exact:true})).toHaveValue('Keep <my> note');await note.getByRole('button',{name:'Save note'}).click();await expect(page.locator('.crm-summary')).toContainText('Keep <my> note');
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Convert to client'}).click();await page.getByRole('button',{name:'Add project',exact:true}).click();const project=page.locator('#crm-project-dialog');await project.getByLabel('Project name').fill('Retainer');await project.getByLabel('Monthly value (EUR)').fill('1500');await project.getByRole('button',{name:'Save project'}).click();await expect(project).toContainText('Project unavailable');await expect(project.getByLabel('Project name')).toHaveValue('Retainer');await project.getByRole('button',{name:'Save project'}).click();await expect(project).toBeHidden();await expect(page.locator('.crm-client')).toContainText('Retainer');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'.cache/sales-os-client-mobile.png',fullPage:true});expect(errors).toEqual([]);
});
test('website metadata is reviewed, duplicate cancellation does not save and palette opens quick note',async({page})=>{
 const {calls}=await fixture(page);await page.goto('/admin/leads');await page.locator('.page-heading [data-add]').click();const form=page.locator('#lead-form');await form.getByLabel('Website',{exact:true}).fill('https://example.com');await form.getByRole('button',{name:'Prefill from website'}).click();await expect(form.getByLabel('Company name')).toHaveValue('Reviewed website name');expect(calls.some(c=>c.a==='crm-create')).toBe(false);page.once('dialog',d=>d.dismiss());await form.getByRole('button',{name:'Save lead'}).click();await expect(form.locator('.crm-duplicates')).toContainText('Fixture Company');expect(calls.some(c=>c.a==='crm-create')).toBe(false);await form.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.keyboard.press('Control+k');const palette=page.locator('#crm-command');await palette.getByRole('searchbox').fill('Fixture');await expect(palette).toContainText('Fixture Company');await palette.getByRole('button',{name:'+ Note',exact:true}).click();await expect(page.locator('#quick-note')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#quick-note')).toBeHidden();
});
