import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';

const companyId='33333333-3333-4333-8333-333333333333',candidateId='22222222-2222-4222-8222-222222222222',reportId='44444444-4444-4444-8444-444444444444';
const example=JSON.parse(await readFile(new URL('../../docs/examples/research-candidates.v1.json',import.meta.url),'utf8')).candidates[0];
const timestamp='2026-09-23T08:00:00Z';
const company={id:companyId,company_name:'Reviewed Furniture',version:3,website:'https://furniture.example',country:'CZ',city:'',industry:'Furniture',short_description:'Manual company description.',services:['Web'],fit:'LOW',priority:'HIGH',pipeline_status:'NEW_LEAD',lead_source:'Google',created_at:timestamp,updated_at:timestamp,archived_at:null};
const provenance={status:'VERIFIED',confidence:'HIGH',evidence:'The official company page records this value.',source_urls:['https://furniture.example/about']};
const research={...example,company_name:company.company_name,city:'Prague',industry:'Interior design',short_description:'Verified revised company description.',research_summary:'Reviewed evidence supports a reusable CGI approach.',source_origin:'ENRICHMENT',last_researched_at:timestamp,field_provenance:{...example.field_provenance,city:provenance,industry:provenance,short_description:provenance}};
const envelope=(value=research,version=3)=>({schema_version:1,company_id:companyId,base_version:version,research:value});
function groups(current,report){return [['city','City'],['industry','Industry'],['short_description','Description'],['services','Services'],['fit','Fit']].map(([key,label])=>{const after=key==='services'?['Product CGI','3D models for architects']:report[key],before=current[key],eligible=JSON.stringify(before)!==JSON.stringify(after)&&!!after&&(key==='services'||key==='fit'||report.field_provenance[key]?.status==='VERIFIED');return {key,label,before,after,protected:Array.isArray(before)?before.length>0:!!before,eligible,reason:eligible?'':key==='industry'?'Industry is inferred and cannot be copied.':'No eligible change.',evidence:key==='services'?report.potential_services:key==='fit'?{fit:report.fit,fit_reason:report.fit_reason}:report.field_provenance[key]};});}
function storedReport(extra={}){return {id:reportId,company_id:companyId,company_version:2,research,selected_fields:['fit'],overwritten_fields:['fit'],before_values:{fit:'MEDIUM'},after_values:{fit:'HIGH'},created_at:timestamp,...extra};}

async function fixture(page,{linked=false,latest=null,archived=false,client=false,reportResearch=research,commitFailures=[],previewFailures=[],previewDelay=0,promptDelay=0,readFailures=0,historyPages=[[]],hasContacts=false}={}){
  const calls=[];let current={...company,archived_at:archived?timestamp:null,pipeline_status:client?'WON':'NEW_LEAD'},insight=latest,history=structuredClone(historyPages),saved=null;
  await page.route('**/api/admin?*',async route=>{const request=route.request(),params=Object.fromEntries(new URL(request.url()).searchParams),action=params.action,body=request.postDataJSON();calls.push({action,params,body,method:request.method()});
    if(action==='me')return route.fulfill({json:{email:'owner@example.test'}});
    if(action==='crm-detail')return route.fulfill({json:{company:current}});
    if(action==='crm-client')return route.fulfill({json:{item:client?{id:'client1',company_id:companyId,version:1,active:true,account_notes:'',client_since:'2026-09-23'}:null}});
    if(action==='crm-research-insight'){if(readFailures-->0)return route.fulfill({status:503,json:{error:'Insight temporarily unavailable.'}});return route.fulfill({json:{company:current,insight:insight||(linked?{id:candidateId,kind:'approved_candidate',research:reportResearch,created_at:timestamp,company_version:1}:null),approved_candidate:linked?{id:candidateId,company_name:current.company_name}:null,has_contacts:hasContacts,history:history[Number(params.page)-1]||[],hasMore:Number(params.page)<history.length,page:Number(params.page)}});}
    if(action==='crm-research-insight-report')return route.fulfill({json:{report:saved||storedReport({research:reportResearch})}});
    if(action==='crm-research-enrich-prompt'){if(promptDelay)await new Promise(resolve=>setTimeout(resolve,promptDelay));return route.fulfill({json:{prompt:'Research the saved business profile and return complete cited ENRICHMENT JSON. Historical research is context.',company:current}});}
    if(action==='crm-research-enrich-preview'){if(previewDelay)await new Promise(resolve=>setTimeout(resolve,previewDelay));const failure=previewFailures.shift();if(failure)return route.fulfill({status:failure,json:{error:'Company changed since this research was prepared.'}});return route.fulfill({json:{company:current,research:body.proposal.research,groups:groups(current,body.proposal.research),warnings:[{message:'Review historical information before accepting it.'}],reviewToken:'review-'+calls.length}});}
    if(action==='crm-research-enrich-commit'){const failure=commitFailures.shift();if(failure)return route.fulfill({status:failure,json:{error:failure===409?'Company changed after preview.':'Enrichment response interrupted.'}});const proposed=body.proposal.research,selected=groups(current,proposed).filter(group=>body.selectedFields.includes(group.key)),before=Object.fromEntries(selected.map(group=>[group.key,group.before])),after=Object.fromEntries(selected.map(group=>[group.key,group.after]));current={...current,...after,version:current.version+1};saved=storedReport({research:proposed,company_version:current.version,selected_fields:body.selectedFields,overwritten_fields:body.overwriteFields,before_values:before,after_values:after});history=[[saved],...history.slice(1)];insight={id:reportId,kind:'enrichment',research:proposed,created_at:timestamp,company_version:current.version};return route.fulfill({json:{company_id:companyId,version:current.version,insight_id:reportId}});}
    if(action==='crm-research-contacts')return route.fulfill({json:{candidate:{id:candidateId,company_name:current.company_name,research_status:'APPROVED',approved_company_id:companyId},company:{id:companyId,company_name:current.company_name,archived_at:null},items:[],can_research:true,can_create:true}});
    if(action==='crm-research-similar-prompt')return route.fulfill({json:{prompt:'A similar-company prompt.',reference:{id:companyId,type:'company',name:current.company_name,status:'NEW_LEAD'},countries:['CZ'],count:10,excluded_count:1}});
    return route.fulfill({json:{items:[],companies:[],projects:[],total:0,page:1,pageSize:25,summary:{},daily:[]}});
  });return {calls,getCompany:()=>current};
}
async function open(page){await page.goto('/admin/leads/'+companyId);await page.getByRole('button',{name:'Enrich company',exact:true}).click();return page.getByRole('dialog');}
async function preview(dialog,value=envelope()){await dialog.getByLabel('Company research JSON',{exact:true}).fill(typeof value==='string'?value:JSON.stringify(value));await dialog.getByRole('button',{name:'Preview enrichment'}).click();await expect(dialog.getByRole('heading',{name:'3. Review the complete AI Insight'})).toBeVisible();}

test('Unlinked company prompt stays read-only; accepting an Insight alone refreshes company version without CRM changes',async({page})=>{
  await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.insightCopied=text;}}}));const {calls,getCompany}=await fixture(page),dialog=await open(page);
  await dialog.getByRole('button',{name:'Prepare prompt'}).click();await expect(dialog.getByLabel('Company research prompt')).toHaveAttribute('readonly','');await expect(dialog.getByLabel('Company research prompt')).toHaveValue(/saved business profile/);await dialog.getByRole('button',{name:'Copy prompt'}).click();expect(await page.evaluate(()=>window.insightCopied)).toContain('ENRICHMENT');await expect(dialog).toContainText('You choose to share it');
  await preview(dialog);await expect(dialog.locator('[data-enrich-select]:checked')).toHaveCount(0);await expect(dialog.getByLabel('Accept this AI Insight',{exact:true})).not.toBeChecked();await expect(dialog.getByRole('button',{name:'Save AI Insight',exact:true})).toBeDisabled();expect(calls.some(call=>call.action==='crm-research-enrich-commit')).toBe(false);
  await dialog.getByLabel('Accept this AI Insight',{exact:true}).check();await dialog.getByRole('button',{name:'Save AI Insight',exact:true}).click();await expect(dialog).toContainText('No company fields were changed.');await dialog.getByRole('button',{name:'Done',exact:true}).click();await expect(page.locator('[data-company-insight]')).toContainText('Insight reviewed:');expect(getCompany()).toMatchObject({...company,version:4});expect(calls.filter(call=>call.action==='crm-detail')).toHaveLength(2);
  const body=calls.find(call=>call.action==='crm-research-enrich-commit').body;expect(body).toMatchObject({companyId,selectedFields:[],overwriteFields:[],acceptInsight:true,confirm:'apply_enrichment'});expect(body.operationId).toMatch(/^[a-f0-9-]{36}$/);await expect(page.locator('[data-company-insight]').getByRole('button',{name:'Find contacts',exact:true})).toHaveCount(0);
});

test('Only selected eligible values apply; every existing value requires its exact replacement acknowledgment',async({page})=>{
  const inferred={...research,field_provenance:{...research.field_provenance,industry:{...provenance,status:'INFERRED'}}}, {calls,getCompany}=await fixture(page),dialog=await open(page);await preview(dialog,envelope(inferred));
  await expect(dialog.locator('[data-enrich-select="industry"]')).toHaveCount(0);await expect(dialog.locator('[data-enrich-group="industry"]')).toContainText('Industry is inferred');await dialog.locator('[data-enrich-select="city"]').check();await dialog.locator('[data-enrich-select="fit"]').check();await dialog.locator('[data-enrich-select="services"]').check();await dialog.getByLabel('Accept this AI Insight',{exact:true}).check();const apply=dialog.getByRole('button',{name:'Apply 3 selected changes',exact:true});await expect(apply).toBeDisabled();
  await dialog.locator('[data-enrich-overwrite="fit"]').check();await expect(apply).toBeDisabled();await dialog.locator('[data-enrich-overwrite="services"]').check();await expect(apply).toBeEnabled();await dialog.locator('[data-enrich-select="fit"]').uncheck();await dialog.locator('[data-enrich-select="fit"]').check();await expect(dialog.locator('[data-enrich-overwrite="fit"]')).not.toBeChecked();await dialog.locator('[data-enrich-overwrite="fit"]').check();await apply.click();await dialog.getByRole('button',{name:'Done',exact:true}).click();
  expect(calls.find(call=>call.action==='crm-research-enrich-commit').body).toMatchObject({selectedFields:['city','services','fit'],overwriteFields:['services','fit']});expect(getCompany()).toMatchObject({city:'Prague',fit:'HIGH',industry:'Furniture',short_description:company.short_description,services:['Product CGI','3D models for architects'],priority:'HIGH',pipeline_status:'NEW_LEAD',version:4});await expect(page.locator('[data-company-insight] .research-insight-fit')).toContainText('HIGH');await expect(page.getByText('Fit: HIGH · manually assessed, separate from priority and engagement.')).toBeVisible();
});

test('Ambiguous writes keep the exact operation and locked choices across closing and reopening',async({page})=>{
  const {calls}=await fixture(page,{commitFailures:[502]});let dialog=await open(page);await preview(dialog);await dialog.locator('[data-enrich-select="city"]').check();await dialog.getByLabel('Accept this AI Insight',{exact:true}).check();await dialog.getByRole('button',{name:'Apply 1 selected change',exact:true}).click();await expect(dialog.locator('[data-enrich-error]')).toContainText('Retry this same accepted enrichment');await expect(dialog.getByLabel('Company research JSON',{exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Enrich company',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.locator('[data-enrich-select="city"]')).toBeChecked();await dialog.getByRole('button',{name:'Retry accepted enrichment'}).click();await expect(dialog.getByRole('heading',{name:'AI Insight saved.'})).toBeVisible();const writes=calls.filter(call=>call.action==='crm-research-enrich-commit');expect(writes).toHaveLength(2);expect(writes[1].body).toEqual(writes[0].body);
});

test('Definite stale conflicts preserve JSON and require a new preview and explicit acceptance',async({page})=>{
  const {calls}=await fixture(page,{commitFailures:[409]}),dialog=await open(page),json=JSON.stringify(envelope());await preview(dialog,json);await dialog.getByLabel('Accept this AI Insight',{exact:true}).check();await dialog.getByRole('button',{name:'Save AI Insight',exact:true}).click();await expect(dialog.locator('[data-enrich-error]')).toContainText('Company changed after preview');await expect(dialog.getByLabel('Company research JSON',{exact:true})).toHaveValue(json);await expect(dialog.getByLabel('Accept this AI Insight',{exact:true})).toHaveCount(0);await dialog.getByRole('button',{name:'Preview enrichment'}).click();await expect(dialog.getByLabel('Accept this AI Insight',{exact:true})).not.toBeChecked();await dialog.getByLabel('Accept this AI Insight',{exact:true}).check();await dialog.getByRole('button',{name:'Save AI Insight',exact:true}).click();const writes=calls.filter(call=>call.action==='crm-research-enrich-commit');expect(writes).toHaveLength(2);expect(writes[1].body.operationId).not.toBe(writes[0].body.operationId);expect(writes[1].body.reviewToken).not.toBe(writes[0].body.reviewToken);
});

test('Linked approved research stays accessible with current Fit, historical report, source evidence and existing contacts action',async({page})=>{
  const {calls}=await fixture(page,{linked:true}),panel=page.locator('[data-company-insight]');await page.goto('/admin/leads/'+companyId);await expect(panel.getByRole('heading',{name:'Current CRM Fit'})).toBeVisible();await expect(panel.locator('.research-insight-fit')).toContainText('LOW');await expect(panel.locator('.research-insight-fit')).toContainText('HIGH');await expect(panel).toContainText('The company has changed since this report');await expect(panel).toContainText('Not recorded in this CRM');await expect(panel.getByRole('link',{name:'View approved research and sources'})).toHaveAttribute('href','/admin/ai-research/'+candidateId);await expect(panel.getByRole('link',{name:'Fictional About page'})).toHaveAttribute('href',research.sources[0].url);
  await panel.getByRole('button',{name:'Find contacts',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Saved contact proposals');await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();await panel.getByRole('button',{name:'Find similar companies',exact:true}).click();await expect(page.getByRole('dialog').getByLabel('Target country codes')).toHaveValue('CZ');expect(calls.filter(call=>call.action==='crm-research-contacts')[0].params.id).toBe(candidateId);expect(calls.some(call=>call.method==='POST')).toBe(false);
});

test('Latest Insight wins while original approved research and paginated immutable reports remain available',async({page})=>{
  const latestResearch={...research,research_summary:'Latest accepted research summary.'},latest={id:reportId,kind:'enrichment',research:latestResearch,created_at:timestamp,company_version:3};const {calls}=await fixture(page,{linked:true,latest,historyPages:[[storedReport()],[storedReport({id:'55555555-5555-4555-8555-555555555555',selected_fields:[],overwritten_fields:[]})]]}),panel=page.locator('[data-company-insight]');await page.goto('/admin/leads/'+companyId);await expect(panel).toContainText('Latest accepted research summary.');await expect(panel.getByRole('link',{name:'View approved research and sources'})).toBeVisible();await panel.getByRole('button',{name:'Next reports'}).click();await expect(panel).toContainText('Page 2');await expect(panel.getByRole('button',{name:'Next reports'})).toBeDisabled();await panel.locator('[data-insight-report]').click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('heading',{name:'Accepted AI Insight.'})).toBeVisible();await expect(dialog).toContainText('Replacement explicitly accepted');await expect(dialog).toContainText('MEDIUM');await expect(dialog).toContainText('HIGH');await expect(dialog).toContainText(research.research_summary);await dialog.getByRole('button',{name:'Close report'}).click();await panel.getByRole('button',{name:'Previous reports'}).click();await expect(panel).toContainText('Page 1');expect(calls.filter(call=>call.action==='crm-research-insight').map(call=>call.params.page)).toEqual(['1','2','1']);expect(calls.every(call=>call.method==='GET')).toBe(true);
});

test('Archived clients retain evidence and history but cannot prepare enrichment',async({page})=>{
  const {calls}=await fixture(page,{archived:true,client:true,linked:true,historyPages:[[storedReport()]],hasContacts:true}),panel=page.locator('[data-company-insight]');await page.goto('/admin/leads/'+companyId);await expect(panel.getByRole('button',{name:'Enrich company',exact:true})).toBeDisabled();await expect(panel.getByRole('button',{name:'Research again',exact:true})).toBeDisabled();await expect(panel).toContainText('Restore this company');await expect(panel).not.toContainText('Not recorded in this CRM');await panel.locator('[data-insight-report]').click();await expect(page.getByRole('dialog')).toContainText('This accepted report is preserved');expect(calls.some(call=>call.action==='crm-research-enrich-prompt')).toBe(false);
});

test('Invalid JSON, wrong company and oversized files stay local; pending previews invalidate on edits and navigation',async({page})=>{
  const {calls}=await fixture(page,{previewDelay:250}),dialog=await open(page),json=dialog.getByLabel('Company research JSON',{exact:true});await json.fill('{');await dialog.getByRole('button',{name:'Preview enrichment'}).click();await expect(dialog.locator('[data-enrich-error]')).toContainText('valid JSON');await json.fill(JSON.stringify({...envelope(),company_id:candidateId}));await dialog.getByRole('button',{name:'Preview enrichment'}).click();await expect(dialog.locator('[data-enrich-error]')).toContainText('another company');await dialog.getByLabel('Company research file').setInputFiles({name:'large.json',mimeType:'application/json',buffer:Buffer.alloc(500001,65)});await expect(dialog.locator('[data-enrich-error]')).toContainText('exceeds 500,000 bytes');expect(calls.filter(call=>call.action==='crm-research-enrich-preview')).toHaveLength(0);
  await json.fill(JSON.stringify(envelope()));await dialog.getByRole('button',{name:'Preview enrichment'}).click();await json.fill('An edited draft');await expect(dialog.getByRole('button',{name:'Preview enrichment'})).toBeEnabled();await expect(dialog.getByLabel('Accept this AI Insight',{exact:true})).toHaveCount(0);await expect(json).toHaveValue('An edited draft');await json.fill(JSON.stringify(envelope()));await dialog.getByRole('button',{name:'Preview enrichment'}).click();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('tab',{name:'Notes',exact:true}).click();await expect(page.getByRole('tabpanel',{name:'Notes'})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);expect(calls.some(call=>call.action==='crm-research-enrich-commit')).toBe(false);
});

test('Prompt copy fallback and late navigation are safe; failed Insight reads can retry',async({page})=>{
  await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw new Error('No clipboard');}}}));const {calls}=await fixture(page,{readFailures:1,promptDelay:200});await page.goto('/admin/leads/'+companyId);await page.getByRole('button',{name:'Retry AI Insight'}).click();await page.getByRole('button',{name:'Enrich company',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Prepare prompt'}).click();await expect(dialog.getByLabel('Company research prompt')).not.toHaveValue('');await dialog.getByRole('button',{name:'Copy prompt'}).click();await expect(dialog.locator('[data-enrich-prompt-status]')).toContainText('Automatic copy is unavailable');expect(await dialog.getByLabel('Company research prompt').evaluate(element=>element.selectionEnd-element.selectionStart)).toBeGreaterThan(50);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Enrich company',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Prepare prompt'}).click();await page.goto('/admin/leads');await expect(page.getByRole('dialog')).toHaveCount(0);expect(calls.every(call=>call.method==='GET')).toBe(true);
});

test('Mobile report and review escape untrusted text and unsafe links without horizontal overflow',async({page})=>{
  const hostile={...research,research_summary:'<img src=x onerror="window.insightInjected=1">',suggested_pitch_angle:'<script>alert(1)</script>',sources:[{url:'javascript:alert(1)',title:'Unsafe source <b>tag</b>',source_type:'About Page',retrieved_at:null,supports:['industry']},{...research.sources[0],url:'https://furniture.example/about?x=1&y=2',title:'Exact source URL'}]},latest={id:reportId,kind:'enrichment',research:hostile,created_at:timestamp,company_version:3};const errors=[];page.on('pageerror',error=>errors.push(error.message));await fixture(page,{latest});await page.setViewportSize({width:390,height:844});await page.goto('/admin/leads/'+companyId);const panel=page.locator('[data-company-insight]');await expect(panel).toContainText(hostile.research_summary);await expect(panel.locator('img,script')).toHaveCount(0);await expect(panel.locator('a[href^="javascript:"]')).toHaveCount(0);await expect(panel.getByRole('link',{name:'Exact source URL'})).toHaveAttribute('href',hostile.sources[1].url);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await panel.evaluate(element=>element.scrollIntoView({block:'start'}));await page.screenshot({path:'.cache/research-insight-mobile.png'});
  await panel.getByRole('button',{name:'Enrich company',exact:true}).click();const dialog=page.getByRole('dialog');await preview(dialog,envelope(hostile));await expect(dialog.locator('img,script')).toHaveCount(0);expect(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth+1)).toBe(true);await page.screenshot({path:'.cache/research-enrich-mobile.png'});expect(await page.evaluate(()=>window.insightInjected)).toBeUndefined();expect(errors).toEqual([]);
});
