import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

test('file sharing migration enforces owner isolation, private sources, immutable links and optimistic versions in Postgres',async()=>{
  const db=new PGlite();
  try {
    await db.exec(`
      create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; create schema crm_private;
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema auth,crm_private to authenticated;
      create table public.presentation_admins(user_id uuid primary key,role text);
      create table public.crm_companies(id uuid primary key,owner_id uuid,archived_at timestamptz,unique(id,owner_id));
      create table public.crm_clients(company_id uuid primary key,owner_id uuid,unique(company_id,owner_id),foreign key(company_id,owner_id) references public.crm_companies(id,owner_id));
      grant select on public.presentation_admins to authenticated;
      grant select,update on public.crm_companies to authenticated;
      grant select on public.crm_clients to authenticated;
      alter table public.crm_companies enable row level security;
      create policy company_owner on public.crm_companies for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
      insert into public.presentation_admins values('11111111-1111-4111-8111-111111111111','owner'),('22222222-2222-4222-8222-222222222222','owner');
      insert into public.crm_companies values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111',null),('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','22222222-2222-4222-8222-222222222222',null);
      insert into public.crm_clients select id,owner_id from public.crm_companies;
    `);
    await db.exec(await readFile(new URL('../supabase/migrations/20260930121806_client_file_shares.sql',import.meta.url),'utf8'));
    await db.exec(`set role authenticated;set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';`);
    const inserted=await db.query(`insert into public.client_file_shares(company_id,owner_id,request_id,title,mega_url,public_token) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',auth.uid(),gen_random_uuid(),'Sofas','https://mega.nz/folder/abcdefgh#AAAAAAAAAAAAAAAAAAAAAA','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa') returning id,version`);
    const id=inserted.rows[0].id;assert.equal(inserted.rows[0].version,1);
    await db.exec(`update public.client_file_shares set active=false where id='${id}' and version=1`);
    assert.equal((await db.query(`select version from public.client_file_shares where id='${id}'`)).rows[0].version,2);
    assert.equal((await db.query(`update public.client_file_shares set active=true where id='${id}' and version=1 returning id`)).rows.length,0);
    await assert.rejects(db.exec(`update public.client_file_shares set public_token=repeat('b',32)`),/permission denied/);
    await assert.rejects(db.exec(`update public.client_file_shares set mega_url='https://mega.nz/folder/ijklmnop#AAAAAAAAAAAAAAAAAAAAAA'`),/permission denied/);
    await assert.rejects(db.exec(`insert into public.client_file_shares(company_id,owner_id,request_id,title,mega_url,public_token) values('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',auth.uid(),gen_random_uuid(),'Other','https://mega.nz/folder/abcdefgh#AAAAAAAAAAAAAAAAAAAAAA',repeat('c',32))`),/Client unavailable|foreign key/);
    await db.exec(`set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222'`);
    assert.equal((await db.query('select * from public.client_file_shares')).rows.length,0);
    assert.equal((await db.query(`update public.client_file_shares set active=true where id='${id}' returning id`)).rows.length,0);
    await db.exec('reset role;set role anon');
    await assert.rejects(db.exec('select mega_url from public.client_file_shares'),/permission denied/);
    await db.exec('reset role;set role service_role');
    assert.equal((await db.query(`select title from public.client_file_shares where public_token=repeat('a',32)`)).rows.length,1);
    await db.exec(`reset role;alter table public.crm_companies add column company_name text default 'Sofa Studio'`);
    await db.exec(await readFile(new URL('../supabase/migrations/20260930125222_client_file_portals_scoped_links.sql',import.meta.url),'utf8'));
    assert.equal((await db.query('select slug from public.client_file_shares')).rows[0].slug,'sofa-studio');
    await db.exec(`set role authenticated;set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';update public.client_file_shares set active=true where id='${id}'`);
    await assert.rejects(db.exec(`update public.client_file_shares set slug='share'`),/check constraint/);
    await assert.rejects(db.exec(`update public.client_file_shares set source_version=9`),/permission denied/);
    await db.exec(`update public.client_file_shares set mega_url='https://mega.nz/folder/ijklmnop#AAAAAAAAAAAAAAAAAAAAAA'`);
    assert.equal((await db.query('select source_version from public.client_file_shares')).rows[0].source_version,2);
    await db.exec(`update public.client_file_shares set slug='sofas'`);
    assert.equal((await db.query('select source_version from public.client_file_shares')).rows[0].source_version,2);
    await assert.rejects(db.exec('insert into public.client_file_links default values'),/permission denied/);
    await db.exec('reset role;set role service_role');
    const insertLink=(node,token,parent='null')=>`insert into public.client_file_links(portal_id,company_id,owner_id,mega_node_id,type,name,token,source_version,parent_id) values('${id}','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','${node}','folder','Models',repeat('${token}',32),2,${parent}) returning id,ancestor_ids`;
    const parent=(await db.query(insertLink('folder01','c'))).rows[0];
    const child=(await db.query(insertLink('folder02','d',`'${parent.id}'`))).rows[0];
    assert.deepEqual(child.ancestor_ids,[parent.id]);
    await assert.rejects(db.exec(insertLink('folder01','e')),/duplicate key/);
    await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222'`);
    assert.equal((await db.query('select * from public.client_file_links')).rows.length,0);
    assert.equal((await db.query(`update public.client_file_links set enabled=false where id='${parent.id}' returning id`)).rows.length,0);
    await db.exec(`set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111'`);
    await assert.rejects(db.exec(`update public.client_file_links set mega_node_id='rootroot'`),/permission denied/);
    await db.exec(`update public.client_file_links set enabled=false where id='${parent.id}' and version=1`);
    assert.equal((await db.query(`select version from public.client_file_links where id='${parent.id}'`)).rows[0].version,2);
    await assert.rejects(db.exec(`update public.client_file_links set enabled=true where id='${parent.id}'`),/revoked link/);
    await db.exec('reset role;set role anon');
    await assert.rejects(db.exec('select token from public.client_file_links'),/permission denied/);
    await db.exec(`reset role;update public.crm_companies set archived_at=now() where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';set role authenticated;set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111'`);
    await assert.rejects(db.exec(`update public.client_file_shares set active=true where id='${id}'`),/Client unavailable/);
    const grants=await db.query(`select has_table_privilege('anon','public.client_file_shares','select') as anonymous_access`);
    assert.equal(grants.rows[0].anonymous_access,false);
    await db.exec('reset role');
    await db.exec(await readFile(new URL('../supabase/migrations/20260930132644_client_file_portal_removal.sql',import.meta.url),'utf8'));
    await db.exec(`set role authenticated;set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111'`);
    await assert.rejects(db.exec(`delete from public.client_file_shares where id='${id}'`),/Client unavailable/);
    await db.exec(`reset role;update public.crm_companies set archived_at=null where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';set role anon`);
    await assert.rejects(db.exec(`delete from public.client_file_shares where id='${id}'`),/permission denied/);
    await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222'`);
    assert.equal((await db.query(`delete from public.client_file_shares where id='${id}' returning id`)).rows.length,0);
    const other=(await db.query(`insert into public.client_file_shares(company_id,owner_id,request_id,title,slug,mega_url,public_token) values('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',auth.uid(),gen_random_uuid(),'Other','other','https://mega.nz/folder/abcdefgh#AAAAAAAAAAAAAAAAAAAAAA',repeat('f',32)) returning id`)).rows[0];
    await db.exec(`reset role;insert into public.client_file_links(portal_id,company_id,owner_id,mega_node_id,type,name,token,source_version) values('${other.id}','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','22222222-2222-4222-8222-222222222222','outside1','file','Other file',repeat('g',32),1);set role authenticated;set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111'`);
    const version=(await db.query(`select version from public.client_file_shares where id='${id}'`)).rows[0].version;
    assert.equal((await db.query(`delete from public.client_file_shares where id='${id}' and version=${version-1} returning id`)).rows.length,0);
    assert.equal((await db.query(`select id from public.client_file_links where portal_id='${id}'`)).rows.length,2);
    assert.equal((await db.query(`delete from public.client_file_shares where id='${id}' and version=${version} returning id`)).rows.length,1);
    await db.exec('reset role');
    assert.equal((await db.query(`select id from public.client_file_links where portal_id='${id}'`)).rows.length,0);
    assert.equal((await db.query(`select id from public.client_file_links where portal_id='${other.id}'`)).rows.length,1);
    assert.equal((await db.query('select * from public.crm_clients')).rows.length,2);
    await db.exec(`set role authenticated;set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';insert into public.client_file_shares(company_id,owner_id,request_id,title,slug,mega_url,public_token) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',auth.uid(),gen_random_uuid(),'Reconnected','sofas','https://mega.nz/folder/abcdefgh#AAAAAAAAAAAAAAAAAAAAAA',repeat('h',32))`);
    assert.equal((await db.query(`select id from public.client_file_shares where public_token=repeat('a',32)`)).rows.length,0);
    assert.equal((await db.query(`select id from public.client_file_shares where slug='sofas'`)).rows.length,1);
  } finally { await db.close(); }
});
