import test from 'node:test';import assert from 'node:assert/strict';
import {parseCSV,exportCSV} from '../public/admin/crm-csv.js';
import {filterConfig} from '../public/admin/crm-filter-config.js';
import {normalizedDomain,normalizedURL,normalizedName,emailDomain} from '../public/admin/crm-normalize.js';
import {publicIPv4,extractMetadata,websiteMetadata} from '../src/crm/website-metadata.js';
import {projectInput} from '../src/crm/clients.js';
import {handleCrm} from '../src/crm/handler.js';
import {EventEmitter} from 'node:events';
test('Website redirects revalidate DNS and transport uses a pinned address',async()=>{
 let calls=0;const get=(url,options,callback)=>{calls++;options.lookup(url.hostname,{},(error,address)=>{assert.equal(address,'93.184.216.34');});const req=new EventEmitter();req.destroy=e=>{req.emit('error',e);req.emit('close');};queueMicrotask(()=>{const res=new EventEmitter();res.statusCode=302;res.headers={location:'http://127.0.0.1/private'};res.resume=()=>req.emit('close');callback(res);});return req;};
 await assert.rejects(()=>websiteMetadata('https://example.test',{get,resolve:async host=>[{address:host==='127.0.0.1'?'127.0.0.1':'93.184.216.34'}]}),/public IPv4/);assert.equal(calls,1);
});
test('Saved filters are strict, serializable and reject ownership/injection',()=>{assert.deepEqual(filterConfig({fit:'HIGH',sort:'name',q:' chair '}),{fit:'HIGH',sort:'name',q:'chair'});for(const v of [{owner_id:'spoof'},{sort:'drop'},{q:[]},[]])assert.throws(()=>filterConfig(v));});
test('Normalization reconciles website variants without inventing company identity',()=>{for(const v of ['https://www.Nario.sk/','www.nario.sk','nario.sk'])assert.equal(normalizedDomain(v),'nario.sk');assert.equal(normalizedName('  Example   Studio '),'example studio');assert.equal(emailDomain('a@COMPANY.sk'),'company.sk');assert.throws(()=>normalizedURL('http://user:pass@example.com'));});
test('Metadata fetch rejects non-public IPv4, IPv6, mixed DNS and nonstandard ports',async()=>{for(const ip of ['127.0.0.1','10.1.1.1','169.254.169.254','172.16.1.1','192.168.0.1','100.64.1.1','198.18.1.1','::1','::ffff:127.0.0.1','224.1.1.1'])assert.equal(publicIPv4(ip),false,ip);assert.equal(publicIPv4('93.184.216.34'),true);await assert.rejects(()=>websiteMetadata('https://example.test',{resolve:async()=>[{address:'93.184.216.34'},{address:'127.0.0.1'}]}));await assert.rejects(()=>websiteMetadata('http://example.test:8080'));});
test('HTML metadata only extracts explicit text and allowed social links',()=>{const d=extractMetadata('<title>Title &amp; Co</title><meta property="og:site_name" content="Real name"><meta name="description" content="Description"><a href="https://www.linkedin.com/company/test">Social</a><script>secret</script>','https://example.com');assert.equal(d.company_name,'Real name');assert.equal(d.short_description,'Description');assert.equal(d.linkedin,'https://www.linkedin.com/company/test');assert.equal(d.country,undefined);});
test('CSV parses quoted commas/newlines, rejects malformed input and neutralizes spreadsheet formulas',()=>{assert.deepEqual(parseCSV('company_name,description\r\n"A, B","one\ntwo ""quoted"""'),[{company_name:'A, B',description:'one\ntwo "quoted"'}]);for(const s of ['company_name\n"oops','company_name,bad\na,b','company_name\na,b','company_name,company_name\na,b'])assert.throws(()=>parseCSV(s));assert.match(exportCSV([{company_name:'=HYPERLINK("x")'}]),/'=HYPERLINK/);});
test('Project values and dates validate independently',()=>{const p=projectInput({name:'Project',status:'ACTIVE',project_value:'0',monthly_value:'1500,25'});assert.equal(Number(p.project_value),0);assert.equal(Number(p.monthly_value),1500.25);assert.throws(()=>projectInput({name:'P',status:'ACTIVE',start_date:'2026-02-30'}));assert.throws(()=>projectInput({name:'P',status:'ACTIVE',start_date:'2026-10-01',end_date:'2026-09-01'}));});
test('CSV preview validates before DB writes; commit requires unchanged review and passes user JWT',async()=>{const id='11111111-1111-4111-8111-111111111111',calls=[],ctx={action:'crm-import-preview',user:{id},token:'jwt',body:{csv:'company_name,country\nNario,SK'},url:new URL('https://test'),call:async(path,opts)=>{assert.equal(opts.token,'jwt');calls.push({path,opts});return path.endsWith('crm_import')?{imported:1,skipped:0}:[];}};const p=await handleCrm(ctx);assert.equal(p.errors.length,0);assert.equal(calls.length,1);await assert.rejects(()=>handleCrm({...ctx,action:'crm-import-commit',body:{...ctx.body,batchId:id,reviewedHash:'wrong',confirm:'import',duplicates:'skip'}}),{status:400});const result=await handleCrm({...ctx,action:'crm-import-commit',body:{...ctx.body,batchId:id,reviewedHash:p.hash,confirm:'import',duplicates:'skip'}});assert.equal(result.imported,1);assert.equal(calls.at(-1).opts.body.p_rows[0].company.pipeline_status,'NEW_LEAD');});
