import {createHash} from 'node:crypto';
import {parseCSV} from '../../public/admin/crm-csv.js';
import {normalizedURL,normalizedDomain,normalizedName} from '../../public/admin/crm-normalize.js';
import {contactInput} from './relations.js';
import {fail,string,uuid,choice} from './validation.js';
export const operationActions=['crm-import-preview','crm-import-commit','crm-sales-report','crm-global-search'];
export async function handleOperations({action,body,url,request,validateCompany}){
 if(action==='crm-global-search')return {items:await request('/rest/v1/rpc/crm_global_search',{method:'POST',body:{p_q:string(url.searchParams.get('q'),160,'search')}})};
 if(action==='crm-sales-report'){const p=url.searchParams,start=p.get('start'),end=p.get('end');for(const v of [start,end])if(!/^\d{4}-\d{2}-\d{2}$/.test(v||'')||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)throw fail(400,'Choose valid report dates.');if(start>end||(Date.parse(end)-Date.parse(start))/86400000>3660)throw fail(400,'Choose a range of at most ten years.');return request('/rest/v1/rpc/crm_sales_report',{method:'POST',body:{p_start:start,p_end:end,p_country:string(p.get('country'),2,'country').toUpperCase(),p_industry:string(p.get('industry'),120,'industry'),p_source:string(p.get('source'),80,'source')}});}
 let raw;try{raw=parseCSV(body.csv);}catch(e){throw fail(400,e.message);}const errors=[],rows=raw.map((r,i)=>{try{const company=validateCompany({company_name:r.company_name,website:normalizedURL(r.website),country:r.country||'',city:r.city||'',industry:r.industry||'',short_description:r.description||'',instagram:r.instagram||'',linkedin:r.linkedin||'',priority:r.priority||'MEDIUM',fit:r.fit||'',lead_source:r.source||'Manual research',pipeline_status:'NEW_LEAD',services:r.services?r.services.split('|').map(s=>s.trim()):[]});const contact=r.contact_name||r.contact_email||r.contact_role?contactInput({full_name:r.contact_name,email:r.contact_email,job_title:r.contact_role,primary_contact:true}):null;return {company,contact};}catch(e){errors.push({row:i+1,error:e.message});return null;}});
 const hash=createHash('sha256').update(body.csv).digest('hex');
 if(action==='crm-import-preview'){const duplicates=errors.length?[]:await request('/rest/v1/rpc/crm_duplicate_batch',{method:'POST',body:{p_rows:rows}});const seen=new Map(),within=[];rows.forEach((r,i)=>{if(!r)return;const keys=[normalizedDomain(r.company.website),normalizedName(r.company.company_name)+'|'+r.company.country].filter(Boolean);for(const key of keys){if(seen.has(key))within.push({row:i+1,earlier:seen.get(key)});else seen.set(key,i+1);}});return {count:raw.length,errors,duplicates,within,hash,preview:raw.map(r=>({company_name:r.company_name,website:r.website,country:r.country}))};}
 if(errors.length)throw fail(400,'Fix CSV validation errors before importing.');if(!uuid(body.batchId)||body.reviewedHash!==hash||body.confirm!=='import')throw fail(400,'Preview and confirm the unchanged CSV first.');const policy=choice(body.duplicates,['skip','create'],'duplicate policy');return request('/rest/v1/rpc/crm_import',{method:'POST',body:{p_id:body.batchId,p_hash:createHash('sha256').update(hash+policy).digest('hex'),p_rows:rows,p_duplicates:policy}});
}
